-- DELETES THE DATABASE IF EXISTS --
DROP DATABASE IF EXISTS gestion_usuario;

-- CREATES THE DATABASE --
CREATE DATABASE gestion_usuarios;
USE gestion_usuarios;

-- CREATING THE TABLES --
CREATE TABLE db_profile (
P_ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
P_EMAIL varchar(50) UNIQUE,
P_USERNAME varchar(40) UNIQUE,
P_PASSWORD varchar(40),
P_NAME varchar(50),
P_LASTNAME varchar(40),
P_TELEPHONE int
);

CREATE TABLE db_user (
U_ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
U_GENDER enum('MALE', 'FEMALE', 'OTHER'),
U_CARD int,
FOREIGN KEY (U_ID) REFERENCES db_profile (P_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE db_admin (
A_ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
A_CURRENT_ACCOUNT int,
FOREIGN KEY (A_ID) REFERENCES db_profile (P_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- INSERTS IN THE TABLES --