-- DELETES THE DATABASE IF EXISTS --
DROP DATABASE IF EXISTS users_manager;

-- CREATES THE DATABASE --
CREATE DATABASE users_manager;
USE users_manager;

-- CREATING THE TABLES --
CREATE TABLE db_profile (
  P_ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
  P_EMAIL varchar(50) UNIQUE,
  P_USERNAME varchar(40) UNIQUE,
  P_PASSWORD varchar(40),
  P_NAME varchar(50),
  P_LASTNAME varchar(40),
  P_TELEPHONE int
);

CREATE TABLE db_user (
  U_ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
  U_GENDER enum('MALE', 'FEMALE', 'OTHER'),
  U_CARD int,
  FOREIGN KEY (U_ID) REFERENCES db_profile (P_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE db_admin (
  A_ID int PRIMARY KEY AUTO_INCREMENT NOT NULL,
  A_CURRENT_ACCOUNT int,
  FOREIGN KEY (A_ID) REFERENCES db_profile (P_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- INSERTS IN THE TABLES --
INSERT INTO db_profile (P_EMAIL, P_USERNAME, P_PASSWORD, P_NAME, P_LASTNAME, P_TELEPHONE) VALUES
('admin@admin.com', 'admin', '1234', "Admin", "Admin", 123456789);

INSERT INTO db_profile (P_EMAIL, P_USERNAME, P_PASSWORD, P_NAME, P_LASTNAME, P_TELEPHONE) VALUES
('user@user.com', 'user', '1234', "User", "User", 987654321);

INSERT INTO db_admin (A_ID, A_CURRENT_ACCOUNT) VALUES
(1, 1000);

INSERT INTO db_user (U_ID, U_GENDER, U_CARD) VALUES
(2, 'MALE', 1234);